[package]
name = "rustish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.27"
os_info = "3.5.1"
sysinfo = "0.26.8"
termcolor = "1.1.3"
whoami = "1.2.3"